[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-mrk.json"

# Option to directly run QEMU with 'cargo run' command
# [target.'cfg(target_os = "none")']
# runner = "bootimage runner"